name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    steps:
    - uses: ./.github/workflows/tests
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: Build release
      run: |
        pip install build
        python3 setup.py bdist_wheel
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*
